version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  backend:
    build: ./backend
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend:/PROJECT_NAME_RAILS_REACT_APP/backend
    ports:
      - "3001:3000"
    depends_on:
      - db
  frontend:
    image: "node:10-alpine"
    user: "node"
    working_dir: /PROJECT_NAME_RAILS_REACT_APP/frontend
    volumes:
      - ./frontend:/PROJECT_NAME_RAILS_REACT_APP/frontend
    ports:
      - "3000:3000"
    command: "yarn start"
    depends_on:
      - backend
